service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post

  
  verifyCode:
    handler: handler.verifyCode
    events:
      - http:
          path: verify
          method: post

  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post

  profile:
    handler: handler.profile
    events:
      - http:
          path: profile
          method: get
          authorizer:
            name: profileAuthorizer
            arn: arn:aws:cognito-idp:ap-south-1:851725365230:userpool/ap-south-1_pAJi67Ofy  (user pool arn (delete it if use))
            type: COGNITO_USER_POOLS